// WorkShop Pro — TypeScript Type Definitions
// src/types/index.ts
// Auto-generated by types-agent — source of truth for all entities

// ─── SHARED ──────────────────────────────────────────────────────────────────

export interface BaseEntity {
  id: string
  createdAt: string   // ISO string
  updatedAt: string
}

export interface PaginationMeta {
  total: number
  page: number
  limit: number
}

export interface ApiResponse<T> {
  data: T
  meta?: PaginationMeta
}

// ─── SITE ────────────────────────────────────────────────────────────────────

export type SiteType   = 'factory' | 'construction' | 'warehouse'
export type SiteStatus = 'active'  | 'paused'       | 'preparing'

export const SITE_TYPE_LABELS: Record<SiteType, string> = {
  factory:      'Xưởng sản xuất',
  construction: 'Công trường',
  warehouse:    'Kho bãi',
}

export const SITE_STATUS_LABELS: Record<SiteStatus, string> = {
  active:    'Hoạt động',
  paused:    'Tạm dừng',
  preparing: 'Chuẩn bị',
}

export interface Site extends BaseEntity {
  code:           string
  name:           string
  type:           SiteType
  industrialZone: string | null
  address:        string
  city:           string | null
  managerId:      string | null
  phone:          string | null
  areaM2:         number | null
  status:         SiteStatus
  notes:          string | null
  // joined
  managerName?:   string
  workerCount?:   number
  projectCount?:  number
}

export interface CreateSiteDto {
  name:           string
  type:           SiteType
  industrialZone?: string
  address:        string
  city?:          string
  managerId?:     string
  phone?:         string
  areaM2?:        number
  status?:        SiteStatus
  notes?:         string
}

// ─── WORKER ──────────────────────────────────────────────────────────────────

export type WorkerStatus  = 'working' | 'on_leave' | 'absent' | 'resigned'
export type Position =
  | 'foreman' | 'deputy_foreman' | 'team_leader' | 'deputy_leader' | 'worker'
  | 'director' | 'deputy_director' | 'chief_accountant' | 'accountant' | 'storekeeper' | 'sales' | 'other'
export type PositionGroup = 'staff' | 'management'

export const POSITION_LABELS: Record<Position, string> = {
  foreman:         'Quản đốc',
  deputy_foreman:  'Phó quản đốc',
  team_leader:     'Tổ trưởng',
  deputy_leader:   'Tổ phó',
  worker:          'Công nhân',
  director:        'Giám đốc',
  deputy_director: 'Phó giám đốc',
  chief_accountant:'Kế toán trưởng',
  accountant:      'Kế toán viên',
  storekeeper:     'Thủ kho',
  sales:           'Sale',
  other:           'Khác',
}

export const STAFF_POSITIONS: Position[] = ['foreman', 'deputy_foreman', 'team_leader', 'deputy_leader', 'worker']
export const MANAGEMENT_POSITIONS: Position[] = ['director', 'deputy_director', 'chief_accountant', 'accountant', 'storekeeper', 'sales', 'other']
export const POSITION_GROUP: Record<Position, PositionGroup> = Object.fromEntries([
  ...STAFF_POSITIONS.map((p) => [p, 'staff']),
  ...MANAGEMENT_POSITIONS.map((p) => [p, 'management']),
]) as Record<Position, PositionGroup>
export const POSITION_GROUP_LABELS: Record<PositionGroup, string> = { staff: 'Nhân viên', management: 'Quản lý' }

export const WORKER_STATUS_LABELS: Record<WorkerStatus, string> = {
  working:   'Đang làm việc',
  on_leave:  'Nghỉ phép',
  absent:    'Vắng mặt',
  resigned:  'Đã nghỉ việc',
}

export interface Worker extends BaseEntity {
  code:             string
  fullName:         string
  gender:           'male' | 'female'
  dateOfBirth:      string | null
  idNumber:         string | null
  phone:            string | null
  address:          string | null
  position:         Position
  specialty:        string | null   // chuyên môn (VD: Hàn kết cấu, Vận hành CNC)
  status:           WorkerStatus
  notes:            string | null
  siteId?:          string | null   // xưởng/công trường công nhân thuộc về (khớp cột site_id ở backend)
  // joined
  activeContract?:  WorkerContract
  // computed (for UI)
  initials:         string   // first letters of name
  avatarColor:      string   // deterministic from id
}

// ─── CONTRACT ────────────────────────────────────────────────────────────────

export type ContractType = 'piece_rate' | 'official' | 'probation'

export const CONTRACT_TYPE_LABELS: Record<ContractType, string> = {
  piece_rate: 'HĐ giao khoán',
  official:   'HĐ chính thức',
  probation:  'HĐ thử việc',
}

export interface WorkerContract extends BaseEntity {
  workerId:                 string
  contractType:             ContractType
  startDate:                string
  endDate:                  string | null
  // salary
  baseSalary:               number | null
  // phụ cấp / tháng
  allowanceResponsibility:  number | null   // Phụ cấp trách nhiệm
  allowanceAttendance:      number | null   // Phụ cấp chuyên cần
  // piece-rate (HĐ giao khoán)
  ratePerUnit:              number | null
  unitName:                 string | null
  isActive:                 boolean
}

export interface CreateContractDto {
  contractType:            ContractType
  startDate:               string
  endDate?:                string
  baseSalary?:             number
  allowanceResponsibility?: number
  allowanceAttendance?:    number
  ratePerUnit?:            number
  unitName?:               string
}

// ─── CUSTOMER (Module 5) ─────────────────────────────────────────────────────

export type CustomerType   = 'domestic' | 'foreign' | 'state' | 'household' | 'individual'
export type CustomerStatus = 'active' | 'inactive' | 'pending'

export const CUSTOMER_TYPE_LABELS: Record<CustomerType, string> = {
  domestic:   'Doanh nghiệp trong nước',
  foreign:    'Doanh nghiệp nước ngoài',
  state:      'Doanh nghiệp nhà nước',
  household:  'Hộ kinh doanh',
  individual: 'Cá nhân',
}

export const CUSTOMER_STATUS_LABELS: Record<CustomerStatus, string> = {
  active:   'Đang hợp tác',
  pending:  'Chờ phản hồi',
  inactive: 'Ngừng hợp tác',
}

export interface CustomerContact {
  id?:        string
  customerId: string
  fullName:   string
  title:      string | null      // Chức vụ
  phone:      string | null
  email:      string | null
  isPrimary:  boolean            // Liên hệ chính → auto-fill báo giá
  sortOrder:  number
}

export interface Customer extends BaseEntity {
  code:                 string
  name:                 string
  type:                 CustomerType
  industry:             string | null
  taxCode:              string | null
  address:              string | null
  website:              string | null
  status:               CustomerStatus
  // Điều khoản mặc định (auto-fill khi tạo báo giá cho KH này)
  defaultValidityDays:  number   // Hiệu lực báo giá (ngày)
  defaultDeliveryDays:  number   // Thời gian giao hàng (ngày)
  defaultPaymentTerms:  string   // '30-25-35-10' | '50-50' | '30-70' | '100-prepay' | 'custom'
  defaultWarrantyNote:  string | null
  defaultSpecialNote:   string | null
  notes:                string | null
  // joined
  contacts?:            CustomerContact[]
  primaryContact?:      Pick<CustomerContact, 'fullName' | 'phone' | 'email'>
  // computed (aggregate)
  projectCount?:        number
  quoteCount?:          number
  totalContractValue?:  number
}

export interface CreateCustomerDto {
  name:                 string
  type:                 CustomerType
  industry?:            string
  taxCode?:             string
  address?:             string
  website?:             string
  status?:              CustomerStatus
  defaultValidityDays?: number
  defaultDeliveryDays?: number
  defaultPaymentTerms?: string
  defaultWarrantyNote?: string
  defaultSpecialNote?:  string
  notes?:               string
  contacts?:            Omit<CustomerContact, 'id' | 'customerId'>[]
}

// ─── PROJECT ─────────────────────────────────────────────────────────────────

export type ProjectStatus =
  | 'planning' | 'in_progress' | 'near_deadline'
  | 'completed' | 'paused'    | 'cancelled'

export type ProjectType = 'commercial' | 'apartment' | 'industrial' | 'art' | 'other'

export const PROJECT_TYPE_LABELS: Record<ProjectType, string> = {
  commercial: 'Thương mại dịch vụ',
  apartment:  'Căn hộ cao cấp',
  industrial: 'Khu công nghiệp',
  art:        'Kiến trúc nghệ thuật',
  other:      'Khác',
}

export const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = {
  planning:      'Lên kế hoạch',
  in_progress:   'Đang thi công',
  near_deadline: 'Sắp bàn giao',
  completed:     'Hoàn thành',
  paused:        'Tạm dừng',
  cancelled:     'Đã hủy',
}

export interface Project extends BaseEntity {
  code:           string
  name:           string
  customerId:     string | null         // FK → customers (Module 5)
  projectType:    ProjectType
  siteId:         string | null         // có thể trống khi dự án tạo nhanh từ báo giá
  contractValue:  number | null
  startDate:      string | null
  deadline:       string
  actualEndDate:  string | null
  progressPct:    number
  status:         ProjectStatus
  description:    string | null
  managerId:      string | null
  // joined
  site?:          Pick<Site, 'id' | 'name'>
  customer?:      Pick<Customer, 'id' | 'name'>
  quoteCount?:    number
  workerCount?:   number
  quotes?:        { id: string; code: string; title: string; status: string }[]  // báo giá liên quan
  hasInstallation?: boolean
}

// ─── QUOTE ───────────────────────────────────────────────────────────────────

export type QuoteStatus = 'draft' | 'pending' | 'approved' | 'rejected' | 'po_received'

export const QUOTE_STATUS_LABELS: Record<QuoteStatus, string> = {
  draft:       'Nháp',
  pending:     'Chờ duyệt',
  approved:    'Đã duyệt',
  rejected:    'Từ chối',
  po_received: 'Có PO',
}

export type PaymentTermsPreset = '30-25-35-10' | '50-50' | '30-70' | '100-prepay' | 'custom'

export const PAYMENT_TERMS_LABELS: Record<PaymentTermsPreset, string> = {
  '30-25-35-10': '30% ký HĐ · 25% triển khai · 35% bàn giao · 10% sau bảo hành',
  '50-50':       '50% trước · 50% khi nhận hàng',
  '30-70':       '30% trước · 70% khi bàn giao',
  '100-prepay':  '100% trước khi nhận hàng',
  'custom':      'Tùy chỉnh',
}

export interface QuoteItem {
  id?:           string
  sectionName:   string | null    // VD: "Cầu thang thép số 1" — NULL nếu không phân section
  sectionNameEn: string | null    // tên section tiếng Anh (bản in song ngữ)
  sortOrder:     number
  itemName:      string
  description:   string | null     // Diễn giải chi tiết (multiline)
  unit:          string
  quantity:      number
  unitPrice:     number
  amount:        number    // computed: quantity * unitPrice
  notes?:        string
}

export interface QuotePaymentStep {
  id?:            string
  stepOrder:      number
  percentage:     number          // VD: 30
  description:    string          // "Tạm ứng khi ký hợp đồng"
  descriptionEn?: string
}

export interface Quote extends BaseEntity {
  code:           string
  projectId:      string
  customerId:     string | null
  contactId:      string | null   // người liên hệ cụ thể
  title:          string
  quoteDate:      string
  validUntil:     string | null
  status:         QuoteStatus
  rejectReason:   string | null
  taxRate:        number          // VAT % — mặc định 8
  validityDays:   number          // Hiệu lực báo giá (ngày)
  deliveryDays:   number          // Thời gian giao hàng (ngày)
  paymentTerms:   PaymentTermsPreset | string
  hasInstallation: boolean
  warrantyNote:   string | null
  contractorNote: string | null   // "Nhà thầu chính cung cấp (miễn phí)"
  notes:          string | null
  // joined
  project?:       Pick<Project, 'id' | 'name'>
  customer?:      Pick<Customer, 'id' | 'name'>
  contact?:       Pick<CustomerContact, 'fullName' | 'phone' | 'email'>
  items?:         QuoteItem[]
  paymentSteps?:  QuotePaymentStep[]
  // computed
  subtotal?:      number
  taxAmount?:     number
  totalAmount?:   number
  itemCount?:     number
  sectionCount?:  number
}

// ─── TASK (KANBAN) ────────────────────────────────────────────────────────────

export type TaskStatus   = 'unassigned' | 'in_progress' | 'paused' | 'completed' | 'cancelled'
export type TaskPriority = 'high' | 'medium' | 'low'

export const TASK_STATUS_LABELS: Record<TaskStatus, string> = {
  unassigned:  'Chưa giao',
  in_progress: 'Đang làm',
  paused:      'Tạm dừng',
  completed:   'Hoàn thành',
  cancelled:   'Đã hủy',
}

export const TASK_PRIORITY_LABELS: Record<TaskPriority, string> = {
  high:   'Ưu tiên cao',
  medium: 'Trung bình',
  low:    'Bình thường',
}

export interface TaskAssignment extends BaseEntity {
  taskId:      string
  workerId:    string
  assignedAt:  string
  startedAt:   string | null
  endedAt:     string | null
  isActive:    boolean
  isOvertime:  boolean
  otEndAt?:    string | null
  transferredFromTaskId?: string
  // joined
  worker?:     Pick<Worker, 'id' | 'code' | 'fullName' | 'initials' | 'avatarColor'>
}

export interface Task extends BaseEntity {
  quoteItemId?:  string
  projectId:     string
  siteId:        string
  title:         string
  description?:  string
  taskDate:      string
  status:        TaskStatus
  priority:      TaskPriority
  sortOrder:     number
  // joined
  section?:      string | null   // danh mục (section_name của hạng mục báo giá nguồn)
  assignments?:  TaskAssignment[]
  activeWorkers?: Pick<Worker, 'id' | 'fullName' | 'initials' | 'avatarColor'>[]
  // lịch sử làm việc (mọi assignment) — cho chi tiết dự án
  workedBy?:     { id: string; fullName: string; initials: string; avatarColor: string }[]
  totalMinutes?: number
  overtimeMinutes?: number
}

/** Hạng mục đã hoàn thành kèm ai làm / tổng giờ / OT (cho panel danh sách hoàn thành). */
export interface CompletedTask extends Task {
  workers: { id: string; fullName: string; initials: string; avatarColor: string }[]
  totalMinutes: number
  overtimeMinutes: number
}

// ─── TIMESHEET ───────────────────────────────────────────────────────────────

export type DayType       = 'workday' | 'leave_paid' | 'leave_unpaid' | 'holiday' | 'absent'
export type TimesheetStatus = 'draft' | 'pending_approval' | 'approved' | 'rejected'

export const DAY_TYPE_LABELS: Record<DayType, string> = {
  workday:      'Đi làm',
  leave_paid:   'Nghỉ có lương',
  leave_unpaid: 'Nghỉ không lương',
  holiday:      'Ngày lễ',
  absent:       'Vắng',
}

export const TIMESHEET_STATUS_LABELS: Record<TimesheetStatus, string> = {
  draft:            'Nháp',
  pending_approval: 'Chờ duyệt',
  approved:         'Đã duyệt',
  rejected:         'Từ chối',
}

export interface TimesheetEntry extends BaseEntity {
  workerId:      string
  workDate:      string
  siteId:        string | null
  regularHours:  number
  overtimeHours: number
  dayType:       DayType
  contractType:  ContractType
  rateNormal:    number | null
  rateOvertime:  number | null
  payAmount:     number    // computed by DB
  status:        TimesheetStatus
  approvedBy?:   string
  approvedAt?:   string
  notes?:        string
  // joined
  worker?:       Pick<Worker, 'id' | 'code' | 'fullName' | 'initials' | 'avatarColor' | 'activeContract'>
}

export interface MonthlySummary {
  workerId:           string
  yearMonth:          string   // 'YYYY-MM'
  totalWorkdays:      number
  totalRegularHours:  number
  totalOtHours:       number
  totalLeaveDays:     number
  totalAbsentDays:    number
  totalPay:           number
  baseSalary:         number | null
  allowance:          number | null
  status:             'open' | 'submitted' | 'approved' | 'paid'
  worker?:            Pick<Worker, 'id' | 'code' | 'fullName'>
}
